name: CI/CD for HostelService

on:
  push:
    branches: [ "main" ]

jobs:
  build_test_and_push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore HostelService.sln

      - name: Build
        run: dotnet build --configuration Release HostelService.sln

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Set image tag
        id: set-tag
        run: echo "::set-output name=image_tag::${{ github.sha }}"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hostelservice:${{ steps.set-tag.outputs.image_tag }} ./HostelService.API

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hostelservice:${{ steps.set-tag.outputs.image_tag }}

  deploy_to_local_runner:
    needs: build_test_and_push
    runs-on: [self-hosted]
    steps:
      - name: Deploy using local runner
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/hostelservice:${{ needs.build_test_and_push.outputs.image-tag }}
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d
